spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    primary:
      hikari:
        jdbc-url: jdbc:h2:mem:test;MODE=MySQL;
        username: sa
        password:
        driver-class-name: org.h2.Driver
    reader:
      hikari:
        jdbc-url: jdbc:h2:mem:test;MODE=MySQL;
        username: sa
        password:
        driver-class-name: org.h2.Driver
  liquibase:
    enabled: false
  redis:
    port: 6378

application:
  host: localhost:8080
  debug: true
